/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_test_testshell_JniUtils */

#ifndef _Included_com_test_testshell_JniUtils
#define _Included_com_test_testshell_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_test_testshell_JniUtils
 * Method:    getCLanguageString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_test_testshell_JniUtils_getCLanguageString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
